language: go

services:
  - mongodb

git:
  depth: 5

go:
  - "1.10.x"

env:
  - CROND_CONFIG_FILE="${GOPATH}/src/github.com/gamelife1314/crontab/.travis.crond.yml"

before_install:
  - wget https://github.com/etcd-io/etcd/releases/download/v3.3.10/etcd-v3.3.10-linux-amd64.tar.gz
  - tar xzf etcd-v3.3.10-linux-amd64.tar.gz
  - nohup ./etcd-v3.3.10-linux-amd64/etcd &
  - go get github.com/mongodb/mongo-go-driver/mongo
  - go get github.com/mongodb/mongo-go-driver/options
  - go get github.com/sirupsen/logrus
  - go get go.etcd.io/etcd/clientv3
  - go get go.etcd.io/etcd/mvcc
  - go get gopkg.in/yaml.v2
  - go get golang.org/x/sys

script:
  - go test -v -cpu=1,2  ./common
  - go test -v -cpu=1,2 ./crond